'use strict';
// tests for authSteamAuthenticate
// Generated by serverless-mocha-plugin

const mod         = require('../functions/auth/steamAuthenticate.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-authSteamAuthenticate'
}

describe('authSteamAuthenticate', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda
    wrapper.init(mod, {
      handler: 'handler'
    });

    done();
  })

  it('should return a redirect URL', (done) => {
    wrapper.run({}, (err, response) => {
      expect(response.redirectURL).is.not.null;
      expect(response.redirectURL.indexOf('https://steamcommunity.com/openid/login')).to.equal(0);
      done();
    });
  });
});
