'use strict';
// tests for authJwtAuthorizer
// Generated by serverless-mocha-plugin

const mod         = require('../functions/auth/jwtAuthorizer.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;
const assert      = require('assert');
const auth        = require('../lib/auth.js');

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-authJwtAuthorizer'
}

describe('authJwtAuthorizer', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda
    wrapper.init(mod, {
      handler: 'handler'
    });

    done()
  })

  it('throws error with no token', (done) => {
    wrapper.run({}, (err, response) => {
      assert(err);
      assert.equal(err.message, 'No Token Present');
      done();
    });
  });

  it('throws error with bad token', (done) => {
    wrapper.run({
      authorizationToken: 'iamnotarealtoken',
      methodArn: 'arn:aws:execute-api:us-east-1:583172113704:j6vxshd7e8/null/GET/'
    }, (err, response) => {
      assert(err);
      assert.equal(err.message, 'jwt malformed');
      done();
    });
  });

  it('returns valid policy with valid token', (done) => {
    const token = auth.sign('blah');

    wrapper.run({
      authorizationToken: token,
      methodArn: 'arn:aws:execute-api:us-east-1:583172113704:j6vxshd7e8/null/GET/'
    }, (err, response) => {
      assert(!err);
      assert.equal(response.principalId, 'blah');

      const statement = response.policyDocument.Statement[0];
      assert.equal(statement.Action, 'execute-api:Invoke');
      assert.equal(statement.Effect, 'Allow');
      assert.equal(statement.Resource, 'arn:aws:execute-api:us-east-1:583172113704:j6vxshd7e8/*');
      done();
    });
  });
});
