'use strict';
// tests for authSteamValidate
// Generated by serverless-mocha-plugin

const mod         = require('../functions/auth/steam.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;
const querystring = require('querystring');
const assert      = require('assert');

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-authSteamValidate'
}

describe('authSteamValidate', () => {
  before(function (done) {
//  wrapper.init(liveFunction); // Run the deployed lambda
    wrapper.init(mod, {
      handler: 'validate'
    });

    done()
  })

  it('parses the steam response properly', (done) => {
    let rawQueryString = "openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197973299801&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197973299801&openid.return_to=http%3A%2F%2Flocalhost%3A8080%2Fsteamreturn&openid.response_nonce=2016-09-12T02%3A14%3A52ZT7LTu6oatqWWwLSdWhDftZfbkdo%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=UX%2FkwcJ%2FbmDmQJFQzvnbuHf0eOs%3D";

    wrapper.run({
      query: querystring.parse(rawQueryString)
    }, (err, response) => {
      console.log(response);
      done();
    });
  });
});
